# workspaces/applications/Cargo.toml:
# Workspace for test applications
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE_MIT.markdown` file in the Veracruz root director for licensing
# and copyright information.

cargo-features = ["resolver"]

[workspace]
members = [
  "crates/examples/data-generators/csv-encoder",
  "crates/examples/data-generators/idash2017-logistic-regression-generator",
  "crates/examples/data-generators/image-processing-generator",
  "crates/examples/data-generators/intersection-set-sum-generator",
  "crates/examples/data-generators/linear-regression-generator",
  "crates/examples/data-generators/moving-average-convergence-divergence-generator",
  "crates/examples/data-generators/number-stream-generator",
  "crates/examples/data-generators/postcard-generator",
  "crates/examples/data-generators/private-set-intersection-generator",
  "crates/examples/data-generators/private-set-intersection-sum-generator",
  "crates/examples/data-generators/shamir-secret-sharing-generator",
  "crates/examples/data-generators/string-generator",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
