[package]
name = "fd-create"
version = "0.3.0"
description = "Test of fd-create function"
authors = ["The Veracruz Development Team"]
edition = "2018"

[dependencies]
anyhow = "1.0.14"
libveracruz = { path = "../../../sdk/rust/libveracruz" }
