[package]
authors = ["The Veracruz Development Team"]
description = "The test program for deserializing postcard encoding on a made-up type and serializing to JSON string. This is for comparison to using native module."
name = "postcard-wasm"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
postcard = { version = "0.7.2", features = [ "alloc", "use-std" ] }
serde = { version = "1.0.3", features = ["derive"] }
serde_json = { version = "1.0" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
